source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EasyIOSXMLPatch_Example', :exclusive => true do
  pod 'EasyIOSXMLPatch', :path => '../'
end

target 'EasyIOSXMLPatch_Tests', :exclusive => true do
  pod 'EasyIOSXMLPatch', :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end

